#!/bin/bash
set -e
set -x

LOCATION=${LOCATION-"gentoo"}
MOUNTS=${1-"dev proc sys usr/portage"}

function cleanup {
	LOCATION=$LOCATION ./umount "$MOUNTS"
}

trap cleanup INT TERM QUIT EXIT

for x in $MOUNTS
do
	mkdir -p $LOCATION/$x
	sudo mount --rbind {/,$LOCATION/}$x
done

if [[ -e /sys/fs/selinux ]]
then
	mount --rbind /sys/fs/selinux $LOCATION/sys/fs/selinux
	mount --bind -o remount,ro $LOCATION/sys/fs/selinux
fi


trap - INT TERM QUIT EXIT
